[package]
name = "aquatic_ws_load_test"
description = "WebTorrent over TLS load tester"
keywords = ["webtorrent", "websocket", "benchmark", "torrent", "bittorrent"]
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

readme = "README.md"

[[bin]]
name = "aquatic_ws_load_test"

[dependencies]
aquatic_common.workspace = true
aquatic_toml_config.workspace = true
aquatic_ws_protocol.workspace = true

anyhow = "1"
async-tungstenite = "0.28"
futures = "0.3"
futures-rustls = "0.26"
glommio = "0.9"
log = "0.4"
mimalloc = { version = "0.1", default-features = false }
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"
rustls = { version = "0.23" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tungstenite = "0.24"

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
